import Link from "next/link";
import { portalHref } from "../lib/site";

export default function Home() {
  return <main>
    <section className="hero"><div className="wrap hero-grid"><div className="hero-copy"><p className="eyebrow">BAY AREA · ADUs + REMODELS</p><h1>More room for <em>what matters.</em></h1><p className="lead">Thoughtful residential construction, from the first sketch to the final walkthrough. We build spaces that feel like they have always belonged.</p><div className="hero-actions"><a className="button button-accent" href={portalHref()}>View project status <span aria-hidden="true">↗</span></a><a className="text-link" href="#services">Explore our work <span aria-hidden="true">↓</span></a></div><div className="hero-note"><span className="line"/> Built with care in the Bay Area</div></div><div className="hero-art" role="img" aria-label="Illustration of a modern backyard accessory dwelling unit"><div className="sun"/><div className="house"><div className="roof"/><div className="wall"><div className="window"><i/><i/></div><div className="door"/><div className="siding"/></div></div><div className="ground"/><div className="plant plant-one"/><div className="plant plant-two"/><div className="art-label">01 / A PLACE TO GROW</div></div></div></section>
    <section className="intro wrap" id="services"><div><p className="eyebrow">WHAT WE DO</p><h2>Good spaces change <em>everyday life.</em></h2></div><p>Whether you are making room for family or giving an old space new purpose, we bring clear plans, careful craft, and an easy working relationship to every job.</p></section>
    <section className="services wrap"><article><span className="service-num">01</span><div className="service-icon">⌂</div><h3>Accessory dwelling units</h3><p>Independent spaces for family, guests, or the next chapter, tailored to your property.</p></article><article><span className="service-num">02</span><div className="service-icon">▤</div><h3>Kitchen remodels</h3><p>A better center of the home, with practical details made for real life.</p></article><article><span className="service-num">03</span><div className="service-icon">◫</div><h3>Whole-home updates</h3><p>Fresh flow, lasting materials, and thoughtful changes that add up.</p></article></section>
    <section className="feature"><div className="wrap feature-grid"><div className="feature-art"><div className="feature-card"><span>FEATURED PROJECT</span><strong>Oakland garden studio</strong><small>Oakland, CA · 2025</small></div></div><div className="feature-copy"><p className="eyebrow">RECENT WORK</p><h2>A little more space. <em>A lot more possibility.</em></h2><p>This light-filled backyard studio gives a growing family a flexible place for work, guests, and the quiet moments in between.</p><Link className="button button-outline" href="/projects">See our projects <span aria-hidden="true">→</span></Link></div></div></section>
    <section className="contact" id="contact"><div className="wrap contact-grid"><div><p className="eyebrow">LET'S TALK</p><h2>Have a space in mind?</h2><p>Tell us what you are dreaming up. We would love to hear about it.</p></div><a className="button button-light" href="mailto:hello@westwoodadu.example?subject=Project%20inquiry">Start a conversation <span aria-hidden="true">↗</span></a></div></section>
  </main>;
}
